version: "3.8"

services:
  mongo:
    image: hub.hamdocker.ir/library/mongo:6.0
    container_name: secure_chat_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  chatroom:
    build: .
    container_name: secure_chat-room
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    env_file:
      - .env  # ✅ Automatically sets MONGODB_URI and email credentials
    restart: unless-stopped  # ✅ optional but good

volumes:
  mongo_data:
